# Generated by Django 4.1.4 on 2023-01-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_projects_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
                ('owner_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.owner_site')),
            ],
        ),
    ]
