# Generated by Django 4.1.4 on 2023-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_owner_site_image_alter_contacts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
