# Generated by Django 4.1.4 on 2023-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
